#!/usr/bin/env python3
"""
Seed regulatory_items table with curated PPA-relevant regulatory events
covering ERCOT, CAISO, and Federal (IRA/ITC/PTC) from 2020-2025.
"""
import os, psycopg2, json
from datetime import date

DATABASE_URL = os.environ["DATABASE_URL"]

ITEMS = [
    # ─── ERCOT ────────────────────────────────────────────────────────────────
    {
        "market": "ERCOT",
        "category": "reliability",
        "title": "SB 3 – Generator Weatherization Mandate (Post-Uri)",
        "summary": "Following Winter Storm Uri (Feb 2021), Texas SB 3 requires thermal generators >10 MW to weatherize to survive a 100-year cold event. Plants must pass PUCT inspection or face decertification. Weatherization costs are not socialized.",
        "detail": "SB 3 passed June 2021 and went into effect immediately. PUCT issued weatherization standards in 16 Tex. Admin. Code §25.55. Generators must submit weatherization plans, pass on-site inspections before each winter season, and maintain performance data. Non-compliance can result in civil penalties up to $1M/day. For PPA diligence: ask sponsors about weatherization spend (typically $2-8/kW for wind) and whether PUCT inspections are current.",
        "effective_date": "2021-06-18",
        "announced_date": "2021-02-28",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=SB3",
        "source_name": "Texas Legislature / PUCT",
        "tags": json.dumps(["weatherization", "reliability", "winter", "thermal", "compliance"]),
        "model_impact": "Add weatherization compliance flag to candidate risk scoring. Wind/solar unaffected for generation; storage and hybrid projects may need battery thermal management upgrades.",
    },
    {
        "market": "ERCOT",
        "category": "market_rules",
        "title": "High System-Wide Offer Cap (HSOCP) Reform",
        "summary": "PUCT raised the Operating Reserve Demand Curve (ORDC) scarcity adder cap from $9,000/MWh to $5,000/MWh effective Dec 2021, then restructured the HSOCP to reduce price spikes while maintaining scarcity signals for investment.",
        "detail": "PUCT Docket 51840. The ORDC-based scarcity pricing was blamed for post-Uri over-payments. The new regime caps the energy+ancillary combined offer at $5,000/MWh. This compressed revenue upside for peaking resources. For battery storage and demand response models: adjust revenue stack to reflect lower peak price ceilings. Merchant tail risk on storage is reduced but so is upside.",
        "effective_date": "2021-12-01",
        "announced_date": "2021-06-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://interchange.puc.texas.gov/Documents/51840_1_1003736.PDF",
        "source_name": "PUCT Docket 51840",
        "tags": json.dumps(["pricing", "scarcity", "ORDC", "market_cap", "battery", "revenue"]),
        "model_impact": "Battery revenue stack: cap ORDC uplift at $5,000/MWh total offer. Reduces P90 storage revenue by ~8-12% vs. pre-2021 assumptions.",
    },
    {
        "market": "ERCOT",
        "category": "reliability",
        "title": "Texas Energy Fund (SB 2627) – $7.2B Dispatchable Generation Loans",
        "summary": "SB 2627 (2023) created the Texas Energy Fund, providing $7.2B in low-interest loans and grants for new dispatchable (gas, nuclear) generation. Renewable projects are explicitly excluded. Adds ~10 GW of firm capacity by 2030.",
        "detail": "The Texas Energy Fund is administered by the Public Utility Commission of Texas. It provides loans at ~3% interest for qualified dispatchable generation projects >100 MW. First round awarded ~$5B to gas projects totaling ~8.5 GW by 2031. This directly competes with renewables on firm capacity, pushes down scarcity price events, and improves summer reliability. For wind/solar PPA modeling: downward pressure on peak prices as new dispatchable capacity comes online 2027-2031.",
        "effective_date": "2023-06-18",
        "announced_date": "2023-06-08",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.puc.texas.gov/agency/resources/pubs/info/tef/",
        "source_name": "PUCT / Texas Energy Fund",
        "tags": json.dumps(["dispatchable", "gas", "reliability", "capacity", "loans", "competition"]),
        "model_impact": "Compress scarcity price assumptions post-2027 for ERCOT wind/solar capture models. Reduces energy arbitrage upside for storage in NCEN/SCEN zones.",
    },
    {
        "market": "ERCOT",
        "category": "interconnection",
        "title": "ERCOT Generator Interconnection Queue Reform (2023-2024)",
        "summary": "ERCOT revised its interconnection study process to adopt a cluster-based 'first ready, first served' approach, replacing the milestone-based queue. Projects must post $50k/MW at signing; studies are now run in cohorts. Reduces speculative queue entries.",
        "detail": "PUCT Docket 56022. Effective January 2024. Key changes: (1) $50,000/MW security deposit required at interconnection agreement signing (vs. milestone deposits); (2) cohort-based studies run quarterly; (3) project must achieve commercial operation within 4 years of COD in application or forfeit; (4) ERCOT can reassign network upgrades among cohort members. Queue dropped from ~185 GW in 2023 to ~140 GW post-reform. For PPA origination: faster study timelines (12-18 months vs. 36 months prior); higher capital commitment earlier reduces speculative projects.",
        "effective_date": "2024-01-01",
        "announced_date": "2023-09-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.ercot.com/mktrules/issues/NOGRR199",
        "source_name": "ERCOT / PUCT Docket 56022",
        "tags": json.dumps(["interconnection", "queue", "reform", "development_risk", "timeline"]),
        "model_impact": "development_risk_score: shorter queue timelines improve score. Queue position within cohort is key. Cohort size in target zone determines shared upgrade costs.",
    },
    {
        "market": "ERCOT",
        "category": "market_rules",
        "title": "Real-Time Co-Optimization (RTCO) – Delayed to 2027",
        "summary": "ERCOT's RTCO project will co-optimize energy and ancillary services in real-time (currently done sequentially). Expected to reduce total system cost by $200M/yr and improve battery storage revenue stacking. Now targeted for Q1 2027 launch.",
        "detail": "ERCOT has been working on RTCO since 2018. The project was delayed multiple times (originally 2023, then 2025, now Q1 2027). Once live, ancillary service prices will move with real-time energy prices, improving price signals. Battery storage revenues are expected to increase 15-25% under RTCO due to better co-optimization of reserve and energy markets. Wind/solar revenues largely unaffected. For battery storage PPA models: flag RTCO as a significant upside driver post-2027.",
        "effective_date": "2027-01-01",
        "announced_date": "2022-01-01",
        "status": "pending",
        "impact_level": "medium",
        "source_url": "https://www.ercot.com/initiatives/rtco",
        "source_name": "ERCOT",
        "tags": json.dumps(["battery", "storage", "ancillary", "co-optimization", "revenue", "2027"]),
        "model_impact": "Battery revenue stack: add RTCO upside scenario post-Q1 2027 (~20% uplift to regulation revenue). Flag in P90/P10 range.",
    },
    {
        "market": "ERCOT",
        "category": "transmission",
        "title": "Panhandle Congestion – CREZ Export Limit",
        "summary": "Competitive Renewable Energy Zones (CREZ) transmission built in 2013 (~3,600 MW capacity) is chronically congested for West Texas wind. DA-RT spreads at HB_WEST and HB_PAN regularly exceed -$10 to -$30/MWh, penalizing wind PPAs in the zone.",
        "detail": "ERCOT's CREZ lines (Oak Circle, Edith Clarke, Barton Creek paths) are fully utilized for most of the year by West Texas wind capacity now exceeding 25 GW in the WEST and PAN zones. ERCOT is studying additional 765kV transmission but no construction timeline is approved. PUCT Docket 54829 for transmission planning. Curtailment rates in WEST zone exceed 6% annually. For PPA diligence: West Texas wind projects face 2-4% additional curtailment annually and -$8 to -$15/MWh basis drag vs. HB_HOUSTON.",
        "effective_date": "2013-01-01",
        "announced_date": "2022-01-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.ercot.com/gridinfo/transmission/CREZ",
        "source_name": "ERCOT Transmission Planning",
        "tags": json.dumps(["congestion", "curtailment", "basis_risk", "west_texas", "CREZ", "wind"]),
        "model_impact": "Direct input: West/PAN zone wind candidates should receive -$8 to -$12/MWh basis adjustment vs. HB_HOUSTON. Curtailment risk score elevated for WEST/PAN zone wind.",
    },
    {
        "market": "ERCOT",
        "category": "market_rules",
        "title": "Dispatchable Reliability Reserve Service (DRRS) – New Product 2024",
        "summary": "ERCOT launched DRRS in June 2024, a new ancillary service product requiring dispatchable resources (gas, storage) to hold 3,000 MW of reserve year-round. Creates a new revenue stream for batteries; increases costs for gas generators that must hold capacity.",
        "detail": "PUCT Docket 54738. DRRS replaces Non-Spinning Reserve Service (Non-Spin) as the primary reliability product. Procured through a day-ahead capacity market mechanism. Price is set through competitive offers. Storage projects can provide DRRS when charged. Expected to clear at $5-15/MWh. Batteries providing DRRS receive capacity payments on top of energy/regulation revenues. For storage PPA models: add DRRS to revenue stack at ~$6/MWh expected value (varies with system conditions).",
        "effective_date": "2024-06-01",
        "announced_date": "2023-12-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.ercot.com/mktrules/issues/NOGRR247",
        "source_name": "ERCOT / PUCT Docket 54738",
        "tags": json.dumps(["ancillary", "battery", "storage", "DRRS", "reserve", "revenue"]),
        "model_impact": "Battery revenue stack: add DRRS layer at $5-10/MWh expected annual average. ERCOT storage projects should include DRRS in financial model.",
    },
    {
        "market": "ERCOT",
        "category": "reliability",
        "title": "Large Load Interconnection – Datacenter Fast-Track (2024-2025)",
        "summary": "PUCT and ERCOT created an expedited interconnection process for large industrial/datacenter loads >75 MW. Loads must post security and commit to a minimum 10-year take-or-pay arrangement. Adds 10-15 GW of new demand by 2030, stressing summer peak capacity.",
        "detail": "Driven by AI/hyperscale datacenter buildout in North Central and South Central Texas. PUCT Docket 57049. Large loads can bypass standard interconnection queue with direct negotiation of transmission service agreement. ERCOT projects peak demand to increase from ~81 GW (2024) to ~95-100 GW by 2030, with datacenters representing 40-50% of new load growth. For PPA origination: positive for energy price signals long-term (tighter capacity margin) but stresses near-term congestion in NCEN.",
        "effective_date": "2024-09-01",
        "announced_date": "2024-04-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://interchange.puc.texas.gov/Apps/ElectricReports/home",
        "source_name": "PUCT Docket 57049",
        "tags": json.dumps(["load_growth", "datacenter", "interconnection", "NCEN", "demand", "capacity"]),
        "model_impact": "Update ERCOT demand curve assumptions: +12-15% load growth by 2030. Improves long-run price expectations for energy sales in NCEN/SCEN. Increases congestion risk in NCEN zone near term.",
    },
    {
        "market": "ERCOT",
        "category": "market_rules",
        "title": "Ancillary Services Redesign – FFR and PFR Products (2022-2023)",
        "summary": "ERCOT introduced Fast Frequency Response (FFR) and Primary Frequency Response (PFR) ancillary services, creating new revenue opportunities for batteries and flywheels. FFR requires response within 500ms; pays separate capacity and energy components.",
        "detail": "ERCOT's grid increasingly relies on inverter-based resources (solar, wind) which provide no inherent inertia. FFR and PFR services fill this gap. Batteries are uniquely positioned to provide both. FFR clears at $0-10/MWh in current markets. PFR is self-provided (no separate market). Also: ERCOT is developing an Inertia service product expected to launch 2026-2027, which could add $3-5/MWh to battery revenue stacks. For battery storage PPAs: include FFR and upcoming Inertia product in revenue stack.",
        "effective_date": "2022-06-01",
        "announced_date": "2022-01-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.ercot.com/mktrules/issues/NOGRR209",
        "source_name": "ERCOT",
        "tags": json.dumps(["ancillary", "battery", "FFR", "PFR", "frequency", "inertia", "storage"]),
        "model_impact": "Battery revenue stack: add FFR at ~$2-4/MWh. Upcoming Inertia product (~2026) adds $3-5/MWh. Both favor 2-hour+ battery storage.",
    },
    {
        "market": "ERCOT",
        "category": "environmental",
        "title": "Texas REC Market – No Renewable Portfolio Standard",
        "summary": "Texas has no active Renewable Portfolio Standard (the original Texas RPS target of 10 GW was exceeded in 2009). RECs trade at $0.50-2.00/MWh in the voluntary market. No compliance demand. PPAs must rely on corporate voluntary demand for REC value.",
        "detail": "Texas originally had a 2% RPS (Senate Bill 7, 1999) which was superseded by actual renewable build. ERCOT RECs (TRECs) trade on WREGIS. Current TREC prices: $0.50-1.50/MWh for wind, $1.00-2.50/MWh for solar (bundled). Corporate voluntary purchasers (Walmart, Google, Microsoft, AT&T) are the primary demand source. For PPA origination: REC revenue is not guaranteed beyond 5-7 years. Bundled PPA is preferred over REC + energy strip. Walmart's Texas footprint: ~3.2 TWh/yr from ERCOT, 100% renewable target by 2035.",
        "effective_date": "2009-01-01",
        "announced_date": "1999-01-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.puc.texas.gov/industry/electric/renewables/rps/",
        "source_name": "PUCT / WREGIS",
        "tags": json.dumps(["REC", "TREC", "renewable", "voluntary", "corporate", "RPS", "WREGIS"]),
        "model_impact": "Add TREC value of $0.50-1.50/MWh to wind PPA revenue. Separate REC and energy strip in deal terms. Flag absence of RPS compliance demand as risk to REC price floor.",
    },

    # ─── CAISO ────────────────────────────────────────────────────────────────
    {
        "market": "CAISO",
        "category": "market_rules",
        "title": "Extended Day-Ahead Market (EDAM) Launch – March 2024",
        "summary": "CAISO launched EDAM in March 2024, extending day-ahead market coordination across 7 Western states (CA, OR, WA, NV, UT, AZ, WY). Reduces renewable curtailment by 15-20% and improves price convergence across the West.",
        "detail": "EDAM builds on the Western Energy Imbalance Market (WEIM) real-time optimization. Under EDAM, resources can offer into a shared day-ahead market clearing across all participating balancing authorities. Expected benefits: reduced renewable curtailment (CAISO solar curtailment was 2.5M MWh in 2023), better transmission utilization, and more stable DA prices. For CAISO PPA models: DA prices become more predictable with EDAM; NP15/SP15 DA premium over real-time expected to compress. Capture rates for solar improve as curtailment falls.",
        "effective_date": "2024-03-01",
        "announced_date": "2022-06-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.caiso.com/market/Pages/EDAM/Default.aspx",
        "source_name": "CAISO",
        "tags": json.dumps(["EDAM", "day_ahead", "curtailment", "western", "solar", "capture_rate"]),
        "model_impact": "Improve CAISO solar capture rate assumptions by 2-4% post-EDAM launch. Reduce curtailment estimate for SP15/NP15 solar by 1.5-2.5%. Reduce DA-RT basis spread.",
    },
    {
        "market": "CAISO",
        "category": "interconnection",
        "title": "FERC Order 2023 – Interconnection Queue Reform (Nationwide)",
        "summary": "FERC Order 2023 (July 2023) requires all ISOs to move to a cluster-based, first-ready-first-served interconnection process with higher financial security requirements. CAISO's implementation targets 15-month study timelines vs. the prior 4-6 year backlog.",
        "detail": "Order 2023 is the most significant interconnection reform in decades. Key provisions: (1) Cluster studies run in cycles (CAISO running ~4 cohorts/yr); (2) $5,000/MW security at readiness milestone; (3) 150MW cluster size maximum; (4) Withdrawal penalty: lose deposits. CAISO had 100+ GW in its queue before reform. Post-reform queue is expected to drop to ~60-70 GW. Study timelines: 15 months cluster study + 3 months agreement negotiation. For PPA origination: development risk reduced for projects with confirmed queue positions in compliant clusters.",
        "effective_date": "2024-06-01",
        "announced_date": "2023-07-28",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.ferc.gov/media/order-no-2023",
        "source_name": "FERC Order 2023",
        "tags": json.dumps(["interconnection", "queue", "FERC", "cluster", "reform", "development_risk"]),
        "model_impact": "development_risk_score: CAISO projects in Order 2023 clusters (post-2024) have materially lower timeline risk. Projects still under prior queue rules carry 3-5 year study delay risk.",
    },
    {
        "market": "CAISO",
        "category": "market_rules",
        "title": "Day-Ahead Market Enhancements (DAME) – Improved Commitment",
        "summary": "CAISO's DAME project (2023-2025) improves unit commitment optimization in the day-ahead market, particularly for variable renewable resources. Reduces next-day renewable curtailment by more accurately scheduling flexible resources.",
        "detail": "DAME is an incremental enhancement to CAISO's existing MRTU day-ahead market. It adds multi-interval optimization for hour-ending commitment, improves ramping constraints for storage, and better represents variable renewable resource availability. Expected to reduce solar over-generation events (duck curve afternoon surplus) by 10-15% through better morning commitment of flexible load and storage. Combined with EDAM, DAME is expected to significantly reduce the volume of renewable curtailment that has grown from 0.5M MWh in 2018 to 2.5M MWh in 2023.",
        "effective_date": "2025-01-01",
        "announced_date": "2023-01-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.caiso.com/market/Pages/DAME/Default.aspx",
        "source_name": "CAISO",
        "tags": json.dumps(["DAME", "curtailment", "solar", "duck_curve", "commitment", "storage"]),
        "model_impact": "Solar capture rate: improve SP15/NP15 solar shape adjustment by 1-2% post-DAME. Storage: better day-ahead dispatch signal improves 4-hour battery capture by 3-5%.",
    },
    {
        "market": "CAISO",
        "category": "environmental",
        "title": "SB 100 – California 100% Clean Electricity by 2045",
        "summary": "California SB 100 (2018) mandates 100% retail electricity from zero-carbon sources by 2045 and 60% by 2030. CPUC is procuring 85+ GW of new clean resources via IRP and contract mandates. Drives massive renewable demand.",
        "detail": "CPUC's 2023 IRP (Integrated Resource Plan) portfolios require 115 GW of new clean generation by 2045. Near-term procurement: CPUC-mandated solicitations have approved contracts for 11.5 GW of new solar, 3.8 GW of storage, and 1.7 GW of offshore wind through 2030. PG&E, SCE, and SDG&E are the primary offtakers. For PPA origination: California load-serving entities must procure rapidly; CPUC-approved standard contract terms provide good template. Long-term price support from SB 100 compliance obligation.",
        "effective_date": "2018-09-10",
        "announced_date": "2018-08-20",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201720180SB100",
        "source_name": "California Legislature / CPUC",
        "tags": json.dumps(["RPS", "clean_energy", "SB100", "procurement", "IRP", "CPUC", "2045"]),
        "model_impact": "Long-run CAISO price premium for clean energy: supports above-market PPA pricing through 2035-2040. CPUC-mandated offtake reduces counterparty risk on utility PPAs.",
    },
    {
        "market": "CAISO",
        "category": "capacity",
        "title": "CPUC Resource Adequacy (RA) Reform – Must-Offer Obligation Expansion",
        "summary": "CPUC reformed its RA program (2022-2024) to add a 72-hour minimum forward showing, expanded flexible RA requirements, and local RA for new zones. Storage must meet energy sufficiency test (4-hour minimum for 100% RA credit).",
        "detail": "CPUC Decision 21-06-029 and subsequent orders. Key changes: (1) Monthly and annual RA now requires resources to show availability for 72 consecutive hours (vs. 4 hours prior); (2) Flexible RA procurement increased to 90% of peak load minus base RA; (3) Storage RA: 4-hour duration required for full capacity credit; shorter storage receives partial credit (2-hour = 50% credit, 1-hour = 25% credit); (4) New local RA zones added (Bay Area, LA Basin refined). For storage PPA origination: 4-hour batteries receive full RA capacity credit (~$4-8/kW-month), shorter storage is penalized.",
        "effective_date": "2022-06-01",
        "announced_date": "2021-06-01",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://docs.cpuc.ca.gov/PublishedDocs/Published/G000/M376/K001/376001023.PDF",
        "source_name": "CPUC Decision 21-06-029",
        "tags": json.dumps(["resource_adequacy", "RA", "storage", "4-hour", "capacity", "CPUC", "battery"]),
        "model_impact": "Storage RA revenue: 4-hour storage = $4-8/kW-month ($48-96/kW-yr) capacity value. Flag sub-4-hour storage as receiving only partial RA credit. Key input for storage LCOE calculation.",
    },
    {
        "market": "CAISO",
        "category": "environmental",
        "title": "NEM 3.0 – Net Energy Metering Reform (2023)",
        "summary": "CPUC NEM 3.0 (April 2023) dramatically reduced export rates for rooftop solar to $0.02-0.08/kWh (from ~$0.25-0.30/kWh), cutting payback periods. Drives shift from rooftop to utility-scale solar and increases battery attachment rates.",
        "detail": "CPUC Decision 22-12-056. Under NEM 3.0, residential solar exports are compensated at 'Avoided Cost Calculator' rates ($0.02-0.08/kWh) rather than retail rates. Existing NEM 1.0/2.0 customers are grandfathered for 15 years. The reform reduces distributed solar economics by 75%, making utility-scale solar relatively more competitive. Battery attachment rates for new solar installations jumped from 15% to 65%+ post-NEM 3.0. For utility-scale PPA origination: reduces distributed solar competition; incremental demand for utility-scale power more likely to come through long-term PPA.",
        "effective_date": "2023-04-15",
        "announced_date": "2022-12-15",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://docs.cpuc.ca.gov/PublishedDocs/Published/G000/M497/K459/497459949.PDF",
        "source_name": "CPUC Decision 22-12-056",
        "tags": json.dumps(["NEM", "rooftop_solar", "distributed", "battery", "retail_rate", "CPUC"]),
        "model_impact": "Utility-scale solar demand: positive tailwind from NEM 3.0 making rooftop less attractive. Battery attachment rate increase improves co-located storage revenue stacks.",
    },
    {
        "market": "CAISO",
        "category": "transmission",
        "title": "California Offshore Wind – CEC 25 GW Target by 2045",
        "summary": "California's Offshore Wind Energy Act (AB 525, 2021) targets 25 GW of offshore wind by 2045, with initial BOEM leasing (5 floating wind areas off Humboldt and Morro Bay). First commercial projects 2030-2035. Requires $10B+ in new transmission.",
        "detail": "CEC submitted its Offshore Wind Strategic Plan (2024). BOEM auctioned 5 lease areas in Dec 2022 for $757M total. Projects: Equinor (Morro Bay, 1.6 GW), RWE (Humboldt, 1.4 GW), Others. First commercial operation not expected before 2031. CAISO is conducting the Transmission Plan for Offshore Wind (TPOW) study to identify grid upgrades needed. Estimated transmission cost: $8-14B. For PPA origination: no near-term opportunity, but long-term demand for floating wind expertise and port infrastructure creates niche. CAISO OASIS prices at NP15 will be affected by large offshore wind injections post-2033.",
        "effective_date": "2021-10-07",
        "announced_date": "2021-10-01",
        "status": "proposed",
        "impact_level": "medium",
        "source_url": "https://www.energy.ca.gov/programs-and-topics/programs/offshore-wind",
        "source_name": "CEC / CAISO / BOEM",
        "tags": json.dumps(["offshore_wind", "BOEM", "transmission", "California", "2045", "floating_wind"]),
        "model_impact": "Long-run NP15 price impact: offshore wind entry post-2033 compresses NP15 mid-day prices. For 2030+ PPA tenors: model NP15 price with offshore wind entry assumption in sensitivity.",
    },
    {
        "market": "CAISO",
        "category": "market_rules",
        "title": "CAISO Flexible Capacity Requirements – Expanded Ramp Obligations",
        "summary": "CAISO expanded flexible RA requirements in 2022-2024, requiring LSEs to hold resources capable of 3-hour continuous ramp. Batteries and hydro qualify best. Increases demand for paired solar+storage projects in CAISO.",
        "detail": "CAISO's Flexible Capacity Requirement (FCR) addresses the 'duck curve' – the steep evening ramp from solar generation going offline. FCR requires ~23 GW of flexible capacity statewide by 2026. Resources must demonstrate ability to ramp continuously for 3 hours. 4-hour batteries with 2C discharge rate are the preferred solution. Solar+storage projects can satisfy both RA (energy) and FCR (flexibility) obligations, making them highly valued by CPUC-regulated utilities. For PPA origination: co-located solar+storage commands 15-25% premium over standalone solar in CAISO utility solicitations.",
        "effective_date": "2022-01-01",
        "announced_date": "2021-06-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.caiso.com/market/Pages/ReliabilityRequirements/FlexibleCapacityRequirements.aspx",
        "source_name": "CAISO / CPUC",
        "tags": json.dumps(["flexible_capacity", "FCR", "duck_curve", "storage", "ramp", "hybrid", "RA"]),
        "model_impact": "Co-located storage premium: add $10-20/kW-yr FCR capacity value for CAISO 4-hour storage. Hybrid solar+storage scores higher on contract_structure dimension.",
    },

    # ─── FEDERAL / IRA ────────────────────────────────────────────────────────
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "Inflation Reduction Act – ITC/PTC Baseline (Section 48E / 45Y)",
        "summary": "IRA (Aug 2022) extended and expanded ITC to 30% base for solar/storage and PTC to $0.0275/kWh for wind/solar. Technology-neutral Sections 48E (ITC) and 45Y (PTC) effective 2025+ for projects starting construction. No project cap; credits phase out when US grid hits 75% clean.",
        "detail": "IRA Section 48E replaces old Section 48 for projects beginning construction after Dec 31, 2024. Section 45Y replaces Section 45. Both provide 6% base credit (30% if Prevailing Wage + Apprenticeship requirements met). Prevailing Wage: must pay Davis-Bacon wage rates for construction, alteration, and repair workers. Apprenticeship: 10-15% of labor hours from registered apprenticeship programs. Credits apply to: solar PV, onshore/offshore wind, battery storage, geothermal, fuel cells, and other zero-emission technologies. Duration: credits phase out when annual electricity production is 75% zero-carbon (estimated ~2032-2035). For PPA modeling: ITC eliminates ~$20-30/MWh of LCOE for solar; PTC adds $27.50/MWh as cash equivalent.",
        "effective_date": "2025-01-01",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.irs.gov/credits-deductions/clean-energy-tax-provisions-of-the-inflation-reduction-act",
        "source_name": "IRS / US Treasury",
        "tags": json.dumps(["ITC", "PTC", "IRA", "tax_credit", "48E", "45Y", "solar", "wind", "storage"]),
        "model_impact": "ITC (30%): reduces solar/storage LCOE by $20-30/MWh. PTC (45Y): $27.50/MWh 10-year cash equivalent for wind/solar. Model both options and take higher NPV. Prevailing wage compliance required for full credit.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRA Energy Community Bonus Credit (+10%)",
        "summary": "Projects in IRS-designated 'Energy Communities' (coal-closure sites, fossil fuel employment counties, brownfields) receive a +10% bonus ITC/PTC adder. Over 1,900 census tracts and most Texas/Appalachia counties qualify.",
        "detail": "IRS Notice 2023-29 (April 2023) defines Energy Communities as: (1) metropolitan or non-metropolitan statistical areas that have/had coal mines or coal/oil/gas plant closures since 2010, and ≥0.17% fossil fuel employment or ≥25% local tax revenue from fossil fuels; (2) brownfield sites. IRS updates qualifying census tracts annually. Currently ~60% of US counties qualify for at least one Energy Community category. Texas qualifies broadly (fossil fuel employment MSAs). For PPA diligence: check IRS EC maps for each project location. If qualifying, adds 10% bonus ITC (total 40% base) or +$0.00275/kWh to PTC.",
        "effective_date": "2023-04-04",
        "announced_date": "2023-04-04",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.irs.gov/pub/irs-drop/n-23-29.pdf",
        "source_name": "IRS Notice 2023-29",
        "tags": json.dumps(["energy_community", "ITC", "PTC", "bonus", "IRA", "coal", "fossil_fuel", "+10%"]),
        "model_impact": "Add EC bonus lookup to candidate scoring (tax_credit_eligibility dimension). If project zip is in EC census tract: ITC becomes 40% (vs 30%), PTC becomes $30.25/MWh (vs $27.50/MWh). Adds $5-10/MWh to project revenue.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRA Domestic Content Bonus Credit (+10%)",
        "summary": "Projects using US-manufactured components (≥40% domestic content for 2025, scaling to 55% by 2026+) receive +10% ITC or +$0.00275/kWh PTC bonus. Drives US manufacturing of solar panels, turbines, and battery cells.",
        "detail": "IRS Notice 2023-38 (May 2023) defines Domestic Content requirements. For solar: ≥40% of 'manufactured components' value must be US-made (excludes cells/wafers for 2023-2025). For wind: nacelle, tower, blade, and electrical components have individual thresholds. For storage: battery cells and modules have US content targets. The domestic content threshold escalates: 40% (2024), 45% (2025), 50% (2026-27), 55% (2028+). US manufacturers: First Solar (modules), Nextracker (trackers), CS Wind (towers), Stion (cells). For PPA diligence: sponsor must certify DC compliance via engineer's attestation. DC bonus adds $4-8/MWh to project economics.",
        "effective_date": "2023-05-12",
        "announced_date": "2023-05-12",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.irs.gov/pub/irs-drop/n-23-38.pdf",
        "source_name": "IRS Notice 2023-38",
        "tags": json.dumps(["domestic_content", "ITC", "PTC", "bonus", "IRA", "manufacturing", "solar", "wind", "+10%"]),
        "model_impact": "PPA diligence checklist: request sponsor's domestic content certification. If DC-compliant, add 10% ITC bonus to LCOE model. Note: DC compliance for solar modules increasingly achievable with First Solar, Hanwha US capacity.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRA Direct Pay (Elective Payment) – Tax-Exempt Entities",
        "summary": "IRA Section 6417 allows tax-exempt entities (municipalities, co-ops, tribes, nonprofits) to receive ITC/PTC as direct cash payments from the US Treasury instead of tax equity. Eliminates need for complex tax equity structures for certain offtakers.",
        "detail": "Direct Pay effectively makes the ITC/PTC refundable for qualifying entities. For-profit developers can elect Direct Pay only for Section 45Q (carbon capture), 45V (hydrogen), and 45U (nuclear) credits. For wind/solar/storage: only tax-exempt counterparties can elect Direct Pay. However, for-profit developers can use TRANSFERABILITY (Section 6418) to sell the ITC/PTC to any corporate buyer for cash at 90-98 cents on the dollar. For Walmart PPA origination: Walmart is a for-profit C-corp; it cannot use Direct Pay. Sponsors can use transferability to monetize credits without Walmart's tax capacity. This broadens the sponsor universe (removes tax equity need).",
        "effective_date": "2023-01-01",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.irs.gov/inflation-reduction-act-of-2022/elective-pay-and-transferability-frequently-asked-questions",
        "source_name": "IRS / US Treasury",
        "tags": json.dumps(["direct_pay", "transferability", "ITC", "PTC", "tax_equity", "IRA", "6417", "6418"]),
        "model_impact": "Transferability reduces PPA counterparty requirement for tax equity. Expand sponsor universe to include developers without established tax equity relationships. PPA pricing: transferability allows 90-98c/$ monetization vs. 75-85c/$ historical tax equity.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRA Standalone Storage ITC – Battery Eligible for 30% Credit",
        "summary": "IRA eliminated the prior requirement that storage be paired with solar to receive ITC. Standalone battery systems now qualify for the 30% ITC (or 40% with Energy Community bonus). Transforms battery storage economics and accelerates standalone deployment.",
        "detail": "Prior to IRA, battery storage only qualified for ITC if charged ≥75% from co-located solar. IRA Section 48(a)(5) expanded the definition of energy property to include standalone storage ≥5 kWh. Standalone storage ITC is effective for projects placed-in-service after Dec 31, 2022. The ITC reduces project CAPEX by 30% (or 40% with EC bonus). For a 200 MW / 800 MWh BESS project at $400/kWh: ITC eliminates $96M of cost → reduces LCOE by $15-20/MWh. For PPA origination: standalone storage ITC fundamentally changes battery economics; no longer requires solar co-location.",
        "effective_date": "2023-01-01",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.irs.gov/pub/irs-drop/n-23-29.pdf",
        "source_name": "IRS / US Treasury",
        "tags": json.dumps(["ITC", "storage", "battery", "standalone", "IRA", "30%", "BESS"]),
        "model_impact": "Standalone battery ITC: subtract 30% (or 40% with EC) from battery CAPEX before LCOE calculation. Reduces BESS LCOE by $15-25/MWh. No longer requires solar pairing — model as independent revenue stack.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "Prevailing Wage & Apprenticeship (PWA) – Required for Full IRA Credits",
        "summary": "IRA credits drop from 30% to 6% if Prevailing Wage (Davis-Bacon) and Apprenticeship requirements are not met during construction. PWA applies to all projects >1 MW beginning construction after Jan 29, 2023. IRS audits are increasing.",
        "detail": "IRS Final Rules (TD 10003, June 2024) clarified PWA requirements. Construction, alteration, and repair workers must be paid Davis-Bacon prevailing wage rates for their locality and trade. Apprenticeship: 12.5% (2023) → 15% (2024+) of labor hours from registered apprenticeship programs. Recordkeeping: payroll records for all covered workers must be maintained for 3 years post-project. Penalty for violation: $5,000/worker violation + back pay. Correction: can cure violations (pay back wages + 180% penalty) within 30 days of IRS notice. For PPA diligence: require sponsor to certify PWA compliance in reps and warranties. Add PWA compliance cost to project CAPEX (~2-5% premium on labor).",
        "effective_date": "2023-01-29",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.federalregister.gov/documents/2024/06/25/2024-13529/prevailing-wage-and-apprenticeship-requirements",
        "source_name": "IRS Final Rules TD 10003",
        "tags": json.dumps(["PWA", "prevailing_wage", "apprenticeship", "Davis-Bacon", "ITC", "PTC", "compliance", "IRA"]),
        "model_impact": "PPA diligence: add 2-4% labor cost premium for PWA compliance. Failure to comply drops credit from 30% ITC to 6% ITC — a $24/MWh swing. Require sponsor certification in term sheet.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRS Energy Community Map – Annual Update & Safe Harbors",
        "summary": "IRS updates Energy Community census tract qualifications annually. Safe harbor: if project began construction in a qualifying tract, it retains EC bonus even if tract later loses qualification. 2024 map expanded qualifying tracts to ~35% of US landmass.",
        "detail": "IRS Notice 2024-30 updated Energy Community definitions and added new qualifying categories for coal closure communities. The IRS maintains an interactive map tool at energycommunities.gov. Projects that 'begin construction' (physical work test or 5% safe harbor) while in a qualifying census tract retain EC status even if annual IRS update later removes the tract. For PPA origination: check energycommunities.gov at project inception; document census tract at construction commencement. ERCOT West Texas and much of Appalachia qualify. Texas Panhandle (Dallam, Hansford, Ochiltree counties) qualifies as fossil fuel employment MSA.",
        "effective_date": "2024-01-01",
        "announced_date": "2024-01-01",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://energycommunities.gov/energy-community-tax-credit-bonus/",
        "source_name": "IRS / DOE Office of Economic Impact",
        "tags": json.dumps(["energy_community", "IRS", "map", "safe_harbor", "census_tract", "ITC", "+10%"]),
        "model_impact": "Screen each candidate by census tract using IRS EC map API. West/PAN zone ERCOT wind: high probability of EC qualification (coal-adjacent counties). Adds $5-10/MWh to project economics.",
    },
    {
        "market": "FEDERAL",
        "category": "interconnection",
        "title": "FERC Order 2023 – National Interconnection Queue Reform",
        "summary": "FERC Order 2023 (July 2023) requires all ISOs/RTOs to implement cluster-based interconnection studies, first-ready-first-served processing, and higher financial security. Effective June 2024 for ERCOT/CAISO/PJM. Reduces 1,500+ GW speculative queue.",
        "detail": "Order 2023 amends the pro-forma Large Generator Interconnection Procedures (LGIP) and LGIP Agreement. Key requirements: (1) Cluster studies (no more individual serial studies); (2) $5,000/MW security at initial acceptance + $10,000/MW at cluster study execution; (3) Ready-to-construct requirements before cluster assignment; (4) Non-refundable withdrawal penalties after cluster assignment; (5) Provisional interconnection service for ready projects. Each RTO has a compliance filing deadline. CAISO, ERCOT, PJM all filed compliance in 2024. Net effect: queue depth drops 40-60%, study timelines compress from 5+ years to 15-24 months.",
        "effective_date": "2024-06-01",
        "announced_date": "2023-07-28",
        "status": "active",
        "impact_level": "high",
        "source_url": "https://www.ferc.gov/media/order-no-2023",
        "source_name": "FERC",
        "tags": json.dumps(["FERC", "interconnection", "queue", "reform", "cluster", "nationwide", "development_risk"]),
        "model_impact": "development_risk_score: projects with Order 2023 cluster position have materially shorter development timelines. Use as input to risk scoring — pre-Order 2023 projects carry timeline risk; post-Order 2023 are better defined.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "Section 45Q – Carbon Capture Tax Credit (Enhanced Under IRA)",
        "summary": "IRA raised Section 45Q credits to $85/tonne CO2 for geological storage and $60/tonne for industrial utilization. Also added Direct Pay eligibility for for-profit developers (unlike ITC/PTC). Relevant for hybrid fossil+CCS projects.",
        "detail": "Section 45Q is the primary federal incentive for carbon capture and storage (CCS). IRA doubled the credit rate and extended the construction start deadline to 2033. Direct Pay is available for all Section 45Q projects (not just tax-exempt entities). This makes 45Q much more bankable than prior versions. For Walmart's renewable portfolio: 45Q is not directly relevant to wind/solar/storage PPA origination but may be relevant if Walmart considers long-duration storage or methane abatement. For grid modeling: CCS projects at existing gas plants in ERCOT could extend the life of dispatchable assets, affecting long-run price forecasts.",
        "effective_date": "2022-08-16",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "low",
        "source_url": "https://www.irs.gov/credits-deductions/carbon-oxide-sequestration-credit",
        "source_name": "IRS / US Treasury",
        "tags": json.dumps(["CCS", "carbon_capture", "45Q", "IRA", "direct_pay", "fossil_fuel"]),
        "model_impact": "Indirect: CCS incentives may extend dispatchable gas asset life in ERCOT, muting long-run scarcity price expectations. Low direct relevance to Walmart wind/solar PPA portfolio.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "IRA Low-Income Community Solar Bonus (+10% or +20%)",
        "summary": "IRA Section 48(e) provides +10% ITC bonus for solar projects in low-income communities and +20% for projects serving low-income housing or benefiting low-income households. Annual 1.8 GW capacity cap managed by DOE.",
        "detail": "DOE's Low-Income Communities Bonus Credit Program (Section 48(e)) opened applications in 2023. Four categories: (1) Facilities in Low-Income Community census tracts: +10%; (2) Facilities on Tribal land: +10%; (3) Facilities part of Qualified Low-Income Residential Building projects: +20%; (4) Facilities providing benefit to Low-Income Economic Benefit projects: +20%. Annual 1.8 GW cap (900 MW per subcategory). Oversubscribed in 2023-2024; lottery selection used. For Walmart PPA origination: community solar projects serving low-income communities could qualify for +20% ITC bonus but are typically <5 MW scale, not utility-scale PPA territory. Relevant for Walmart's community solar subscription programs.",
        "effective_date": "2023-01-01",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "low",
        "source_url": "https://www.energy.gov/justice/low-income-communities-bonus-credit-program",
        "source_name": "DOE Office of Economic Impact and Diversity",
        "tags": json.dumps(["low_income", "community_solar", "ITC", "+20%", "IRA", "48e", "tribal"]),
        "model_impact": "Low relevance for utility-scale PPA origination (1.8 GW cap fills quickly with distributed projects). Flag for any co-located community benefit programs in Walmart's ESG reporting.",
    },
    {
        "market": "FEDERAL",
        "category": "tax_credits",
        "title": "MACRS 5-Year Bonus Depreciation – IRA Extension",
        "summary": "Renewable energy projects remain eligible for MACRS 5-year bonus depreciation (60% in 2024, 40% in 2025, 20% in 2026, 0% in 2027+). Combined with ITC, provides substantial first-year cash benefit. Bonus depreciation cliff in 2027 increases time pressure for project finance.",
        "detail": "MACRS 5-year depreciation applies to wind, solar, storage, and other energy property. Under Tax Cuts and Jobs Act (2017), 100% bonus depreciation was available through 2022, now phasing down: 60% (2024), 40% (2025), 20% (2026). Combined with ITC, the after-tax cost of a solar project is reduced by ~40-45% in year 1 when full depreciation is taken. Tax equity investors use accelerated depreciation in partnership flip structures. For PPA modeling: projects that achieve COD by 2024-2026 can still capture significant depreciation benefit. Post-2026 projects lose this benefit absent Congressional action.",
        "effective_date": "2017-12-22",
        "announced_date": "2017-12-22",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.irs.gov/pub/irs-pdf/p946.pdf",
        "source_name": "IRS Publication 946",
        "tags": json.dumps(["MACRS", "depreciation", "bonus", "tax_equity", "ITC", "5-year", "partnership_flip"]),
        "model_impact": "Project finance: 60% bonus depreciation (2024) combined with 30% ITC reduces after-tax cost by ~40%. Model depreciation benefit separately in LCOE vs. energy price calculation. Phase-down post-2026 increases urgency for early COD.",
    },
    {
        "market": "FEDERAL",
        "category": "market_rules",
        "title": "DOE Loan Programs Office (LPO) – Title XVII Expansion",
        "summary": "IRA provided $40B in new loan guarantee authority to DOE LPO. Title XVII now covers energy storage, transmission, advanced nuclear, and clean hydrogen. Rates at Treasury rate + minimal spread (~5-6%). Transforms large project finance for clean energy.",
        "detail": "DOE LPO's Title XVII Innovative Energy Loan Guarantee Program received $40B in IRA funding. Notable recent loans: 500 MW Nevada geothermal project ($1.1B), offshore wind port infrastructure ($91M), multiple utility-scale storage projects. LPO also has a $10B Tribal Energy Loan Guarantee. Key advantage: LPO loans are non-recourse project finance at sovereign-adjacent rates (5-6% vs. commercial 7-9%). For PPA origination: projects with LPO financing are lower-cost and can offer more competitive PPA prices. LPO financing also improves sponsor creditworthiness. Check if sponsor projects are LPO-financed.",
        "effective_date": "2022-08-16",
        "announced_date": "2022-08-16",
        "status": "active",
        "impact_level": "medium",
        "source_url": "https://www.energy.gov/lpo/title-xvii",
        "source_name": "DOE Loan Programs Office",
        "tags": json.dumps(["DOE", "LPO", "loan_guarantee", "Title_XVII", "project_finance", "storage", "transmission"]),
        "model_impact": "Sponsor quality: LPO-financed projects have lower cost of capital → more competitive PPA pricing. Flag LPO financing in sponsor quality dimension scoring.",
    },
]

def seed():
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS regulatory_items (
            id              SERIAL PRIMARY KEY,
            market          VARCHAR(10) NOT NULL,
            category        VARCHAR(30) NOT NULL,
            title           TEXT NOT NULL,
            summary         TEXT NOT NULL,
            detail          TEXT,
            effective_date  DATE,
            announced_date  DATE,
            status          VARCHAR(20) NOT NULL,
            impact_level    VARCHAR(10) NOT NULL,
            source_url      TEXT,
            source_name     TEXT,
            tags            TEXT,
            model_impact    TEXT,
            scraped_at      TIMESTAMPTZ DEFAULT NOW(),
            created_at      TIMESTAMPTZ DEFAULT NOW()
        )
    """)

    cur.execute("SELECT COUNT(*) FROM regulatory_items")
    count = cur.fetchone()[0]
    if count > 0:
        print(f"Table already has {count} rows. Truncating and reseeding...")
        cur.execute("TRUNCATE TABLE regulatory_items RESTART IDENTITY")

    insert_sql = """
        INSERT INTO regulatory_items
          (market, category, title, summary, detail, effective_date, announced_date,
           status, impact_level, source_url, source_name, tags, model_impact)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """

    for item in ITEMS:
        cur.execute(insert_sql, (
            item["market"],
            item["category"],
            item["title"],
            item["summary"],
            item.get("detail"),
            item.get("effective_date"),
            item.get("announced_date"),
            item["status"],
            item["impact_level"],
            item.get("source_url"),
            item.get("source_name"),
            item.get("tags"),
            item.get("model_impact"),
        ))

    conn.commit()
    cur.close()
    conn.close()
    print(f"Seeded {len(ITEMS)} regulatory items.")

if __name__ == "__main__":
    seed()
